name: car_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  persistent_bottom_nav_bar: ^6.2.1
  supabase_flutter: ^2.8.1

dev_dependencies:
  dart_code_linter: ^1.2.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Lora,Poppins,Roboto/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Lora,Poppins,Roboto/Poppins/Poppins-Bold.ttf
          weight: 700
